apiVersion: v1
kind: Pod
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  containers:
    - name: mongo-db-container
      image: mongo
      ports:
        - containerPort: 27017
      env: 
        - name: "MONGO_INITDB_ROOT_USERNAME"
          value: "imperialbet"
        - name: "MONGO_INITDB_ROOT_PASSWORD"
          value: "123456"