apiVersion: apps/v1
kind: Deployment
metadata:
  name: primepix-deployment
spec:
  selector:
    matchLabels:
      app: primepix
      version: v1
  replicas: 2
  template:
    metadata:
      labels:
        app: primepix
        version: v1
    spec:
      containers:
      - name: primepix-container
        imagePullPolicy: Never
        image: bernavaguilherme/primepix
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 3