apiVersion: v1
kind: Pod
metadata:
  name: primepix
  labels:
    app: primepix
spec:
  containers:
    - name: primepix-container
      imagePullPolicy: Never
      image: bernavaguilherme/primepix
      ports:
        - containerPort: 80